server:
  port: 8888

spring:
  profiles:
      active: git

logging:
  level:
      org.springframework.cloud.config: DEBUG

---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: D:\Projects\puffproject\cloud-configuration
          searchPaths: backend,backend/*
          cloneOnStart: true