spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/puffproject/cloud-configuration.git
          searchPaths: backend,backend/*
          cloneOnStart: true

logging:
  level:
      org.springframework.cloud.config: DEBUG