server:
  port: 8888

spring:
  profiles:
      active: git

logging:
  level:
      org.springframework.cloud.config: DEBUG

keycloak:
  realm: puff
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: config-server
  principal-attribute: preferred_username
  bearer-only: true

---
spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: D:\Projects\puffproject\cloud-configuration
          searchPaths: backend,backend/*
          cloneOnStart: true